# Generated by Django 4.1.dev20220407055456 on 2022-04-11 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="releasetrack",
            options={"ordering": ["release", "track_number"]},
        ),
    ]
